- name: Add RPM Fusion Free GPG key
  become: true
  ansible.builtin.rpm_key:
    fingerprint: "{{ rpmfusion_free_fingerprint }}"
    key: "{{ rpmfusion_free_gpg_key }}"
    state: present
  when: ansible_facts['distribution'] == "Fedora"

- name: Add RPM Fusion Free repository
  become: true
  ansible.builtin.dnf:
    name: "{{ rpmfusion_free_repository }}"
    state: present
  when: ansible_facts['distribution'] == "Fedora"

