- name: Install RPM Fusion free and nonfree
  when: ansible_facts['distribution'] == "Fedora"
  block:
    - name: Configure RPM Fusion free
      block:
        - name: Add RPM Fusion free GPG key
          become: true
          ansible.builtin.rpm_key:
            fingerprint: "{{ rpmfusion_free_fingerprint }}"
            key: "{{ rpmfusion_free_gpg_key }}"
            state: present

        - name: Add RPM Fusion free repository
          become: true
          ansible.builtin.dnf:
            name: "{{ rpmfusion_free_repository }}"
            state: present
          notify:
            - Perform dnf update

    - name: Configure RPM Fusion nonfree
      block:
        - name: Add RPM Fusion nonfree GPG key
          become: true
          ansible.builtin.rpm_key:
            fingerprint: "{{ rpmfusion_nonfree_fingerprint }}"
            key: "{{ rpmfusion_nonfree_gpg_key }}"
            state: present
            
        - name: Add RPM Fusion nonfree repository
          become: true
          ansible.builtin.dnf:
            name: "{{ rpmfusion_nonfree_repository }}"
            state: present
          notify:
            - Perform dnf update
