- name: Add RPM Fusion Free GPG key
  become: true
  ansible.builtin.rpm_key:
    key: "{{ rpmfusion_free_gpg_key }}"
    state: present

- name: Add RPM Fusion Free repository
  become: true
  ansible.builtin.dnf:
    name: "{{ rpmfusion_free_repository }}"
    state: present
