---
- name: Setup a workstation
  hosts: "{{ target }}"
  connection: local # we're debugging, so the hosts may not exist

  tasks:
    - name: Include base role to install standard packages
      ansible.builtin.include_role:
        name: base

    - name: Include other roles based on workstation type
      when: workstation_roles is defined
      ansible.builtin.include_role:
        name: "{{ item }}"
      with_first_found:
        - "{{ groups['workstation'] | map('extract', hostvars, ['workstation_roles']) | list }}"
        - "{{ groups['workstation'] | map('extract', hostvars, ['workstation_roles']) | list }}"
