---
- name: Setup a workstation
  hosts: "{{ target }}"
  connection: local # we're debugging, so the hosts may not exist

  tasks:
    # Testing
    #- name: Check memory and free space
    #  ansible.builtin.assert:
    #    that:
          # Check that the system has over 1GB of memory and
          # 20GB of disk space free
    #      - "ansible_facts.memfree_gb > 1"
    #      - "ansible_facts.diskfree_gb > 20"
    
    # Provisioning
    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ workstation_roles }}"
