---
- name: Setup a workstation
  hosts: "{{ target }}"
  connection: local # no need for ssh

  tasks:
    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ workstation_roles }}"
