---    
- name: Include OS-specific variables
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - default.yml
      paths:
        - "vars"

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - default.yml
