---
- name: Include OS-specific varables
  ansible.builtin.include_vars: "{{ _item }}"
  loop_control:
    loop_var: _item
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Print variable
  ansible.builtin.debug:
    msg: "Name of package: {{ package_name }}"

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "{{ role_path }}/tasks"
      skip: true
