---
- name: Include variables from the first found file
  ansible.builtin.set_fact:
    vars_file: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "vars"
  when: vars_file is not none

- name: Skip task if no file found
  ansible.builtin.debug:
    msg: "No file found, skipping task"
  when: vars_file is none
  
- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - default.yml
