---
- name: Debug message audacity
  ansible.builtin.debug:
    msg: "Installing audacity"

- name: Install audacity
  become: true
  ansible.builtin.package:
    name: "{{ package_name }}"
    state: present