---
- name: Install Flatpak
  become: true
  ansible.builtin.package:
    name: "{{ package_name }}"
    state: present

- name: Add the Flathub repository
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: "{{ flatpak_flathub_repo_url }}"
    state: present