---
- name: Install flatpak
  become: true
  ansible.builtin.package:
    name: "{{ package_name }}"
    state: present

- name: Install Flathub remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: "{{ flatpak_flathub_repo_url }}"
    state: present
