- name: Copy wallpaper files
  ansible.builtin.copy:
    src: wallpapers/
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/backgrounds/"
    mode: '0644'

- name: Set wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/backgrounds/0004.jpg'"

- name: Configure wallpaper position
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: Configure keyboard layouts
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us'), ('xkb', 'hu'), ('xkb', 'ro+std')]"