---
- name: Add Chrome repository
  become: true
  ansible.builtin.yum_repository:
    file: google-chrome
    name: google-chrome
    enabled: true
    gpgcheck: true
    description: google-chrome
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64

- name: Install Chrome
  become: true
  ansible.builtin.dnf:
    name: google-chrome-stable
    state: present
