---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: opensuse
    image: docker.io/zoliky/opensuse-leap:15.5
    pre_build_image: true
  - name: opensuse-tumbleweed
    image: docker.io/zoliky/opensuse-tumbleweed:latest
    pre_build_image: true
provisioner:
  name: ansible


