---
driver:
  name: podman
platforms:
  #- name: instance
  #  image: quay.io/centos/centos:stream8
  #  pre_build_image: true
  - name: debian12
    image: docker.io/geerlingguy/docker-debian12-ansible
    pre_build_image: true
    systemd: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
    privileged: true
    command: "/sbin/init"
provisioner:
  name: ansible

